# Use the new container-based infrastructure
sudo: false

# Install some apt packages needed for spcomp
addons:
    apt:
        sources: 
            - deadsnakes
        packages:
            - lib32stdc++6
            # We need at least python3.4 to run our custom deployment scripts
            - python3.5

# Set the build environment
env:
    global:
        - PROJECT_SHORTNAME="tf2_taunts_tf2idb"
        - UPDATER_REPO="sm_updater_plugins"
        - UPDATER_USER="fakuivan"
        - UPDATER_USER_NAME="$UPDATER_USER"
        - UPDATER_USER_EMAIL="$UPDATER_USER@gmail.com"
        - PROJECT_REPO_URL="https://github.com/$UPDATER_USER/TF2-Taunts-TF2IDB"
    matrix:
        - SM_VERSION=1.10 CACHE_BUILDER=tf2idb
        - SM_VERSION=1.10 CACHE_BUILDER=tf2ii
        - SM_VERSION=1.11 CACHE_BUILDER=tf2idb
        - SM_VERSION=1.11 CACHE_BUILDER=tf2ii

# Allow the experimental branch to fail
matrix:
    fast_finish: true
    allow_failures:
        - env: SM_VERSION=1.11

install:
    - cd "$TRAVIS_BUILD_DIR"
    - mkdir .smlib
    - (cd .smlib/ &&
      wget --input-file="http://sourcemod.net/smdrop/$SM_VERSION/sourcemod-latest-linux" &&
      tar -xzf "$(cat sourcemod-latest-linux)")
    - export SM_SCRIPTING_PATH=./.smlib/addons/sourcemod/scripting
    - chmod +x "$SM_SCRIPTING_PATH/spcomp64"
    - export GIT_COMMIT_NUMBER="$(git rev-list --count HEAD)"
    - |
      if [[ -z "$TRAVIS_TAG" ]]; then
          GIT_TAG="$(git describe --tags || echo _untagged_)"
      else
          GIT_TAG="$TRAVIS_TAG";
      fi
      export GIT_TAG

before_script:
    - cd "$TRAVIS_BUILD_DIR"
    - UPDATER_BRANCH="$TRAVIS_BRANCH"
    # Tagged releases only count if this is the master branch, else only updater releases will be used
    - '[[ "$TRAVIS_BRANCH" = "$GIT_TAG" ]] || [[ "$TRAVIS_BRANCH" = "updater" ]] && UPDATER_BRANCH="master"'
    - UPDATER_PROJECT_DIRECTORY="$PROJECT_SHORTNAME-$CACHE_BUILDER"
    - UPDATER_URL="https://raw.githubusercontent.com/$UPDATER_USER/$UPDATER_REPO/$UPDATER_BRANCH/$UPDATER_PROJECT_DIRECTORY/updater.txt"
    - export UPDATER_URL UPDATER_NEWS_URL="$PROJECT_REPO_URL"
    - '[[ "$CACHE_BUILDER" = "tf2ii" ]] && export PLUGIN_USE_TF2II=true'

script: 
    - make all

before_deploy:
    - cd "$TRAVIS_BUILD_DIR"
    - RELEASE_ARTIFACT="$TRAVIS_BUILD_DIR/tf2_taunts_tf2idb-n$GIT_COMMIT_NUMBER-$CACHE_BUILDER.zip"
    - OUTPUT_DIR="$(make print-output-dir)"
    - (cd "$OUTPUT_DIR" && zip -r "$RELEASE_ARTIFACT" .)

# Notifications
notifications:
    email: false
